config/routes.rb
Rails.application.routes.draw do
  
  resources :topics, only: [:index, :show]
  
  get 'topics/index'

  get 'topics/show'

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  
  get 'about', to: 'pages#about'

  get 'contact', to: 'pages#contact'
  
  get 'contact', to: 'pages#contact'
  
  get 'update_params', to: 'pages#update'
  
  # get 'tech-news', to: 'pages#tech_news'

  resources :portfolios, except: [:show]
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p class="app-footer"><%#= copyright_generator %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Jared Johnson</h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">My Blog</h1>
    <p class="lead blog-description">Random stuff that i randomly post</p>
    <span>
      <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %>
    </span>
    <span>
      <%= link_to "Topics", topics_path %>
    </span>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded blog-nav">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="container">
    <%= link_to "Jared Johnson", root_path, class: 'navbar-brand' %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <%= nav_helper 'nav-link', 'li' %>  
        <%= login_helper 'nav-link' %>  
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<div class="col-md-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>If you cant read the blog posts, you are not alone. Google translate cant even read them.</p>
  </div>
  
  <h4>Topics</h4>
    <% @side_bar_topics.each do |topic| %>
      <p><%= link_to topic.title, topic_path(topic) %></p>
    <% end %>
  </div>
 
  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://github.com/jereto101/ruby_on_rails_c9"><%= fa_stacked_icon "github" %> Github</a></li>
      <li><a href="http://www.twitter.com/"><%= fa_stacked_icon "twitter"%> Twitter</a></li>
      <li><a href="http://www.facebook.com/"><%= fa_stacked_icon "facebook"%> Facebook</a></li>
      <li><a href="http://www.youtube.com/"><%= fa_stacked_icon "youtube"%> Youtube</a></li>
      <li><a href="www.swgalaxymap.com/"><%= fa_stacked_icon "ra"%></a> / <a href="www.starwarsstreetview.com/"><%= fa_stacked_icon "first-order"%></a></li>
    </ol>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="<%=location%>">
  <%= link_to "Home", root_path %>
  <%= link_to "About", about_path %>
  <%= link_to "Contacts", contact_path %>
  <%= link_to "Blogs", blogs_path %>
  <%= link_to "Portfolios", portfolios_path %>
</div>